Excel2dll.exe -config config -s -out out

copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\HeroConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\SkillConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\BuffConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\ItemConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\BattleUnitConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\ShopConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\PlayerConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\FormulaLearnAttrConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\JobConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\WorldConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\ForceConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\CityBuildingConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\CityDevConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\CityAttrConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\SeasonConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"
copy "D:\U3dPrj\SanKingdom\Design\out\Csharp_s\ArmsConfig_s.cs" "D:\U3dPrj\SanKingdom\Assets\Resources\Scripts\Configs\"